# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lnk < Formula
  desc "Git-native dotfiles management that doesn't suck"
  homepage "https://github.com/yarlson/lnk"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/lnk/releases/download/v0.2.2/lnk_Darwin_x86_64.tar.gz"
      sha256 "3db3e47b344322baa63240f72eb12a506cec4dc5255f27a985489e6144212743"

      def install
        bin.install "lnk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/lnk/releases/download/v0.2.2/lnk_Darwin_arm64.tar.gz"
      sha256 "0cbbd663f9e3a80c696d5013965be2200b92d49de9db4662b349414eb0a9ba1c"

      def install
        bin.install "lnk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/lnk/releases/download/v0.2.2/lnk_Linux_x86_64.tar.gz"
      sha256 "cbfc026cff64883163c946273a77e347190b8cdb682b2354c88e3af980d95252"
      def install
        bin.install "lnk"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/lnk/releases/download/v0.2.2/lnk_Linux_arm64.tar.gz"
      sha256 "68fa899907f5baf8efff9f25a9224de4be036b126b2c84c2a62c353ad4b94409"
      def install
        bin.install "lnk"
      end
    end
  end

  test do
    system "#{bin}/lnk --version"
  end
end
