# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lnk < Formula
  desc "Git-native dotfiles management that doesn't suck"
  homepage "https://github.com/yarlson/lnk"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/lnk/releases/download/v0.5.0/lnk_Darwin_x86_64.tar.gz"
      sha256 "9b70865a99de29dd2e796778879d251848b2bb23bc49b9bc32c6f78dcf60d48d"

      def install
        bin.install "lnk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/lnk/releases/download/v0.5.0/lnk_Darwin_arm64.tar.gz"
      sha256 "50a629f4f73bc3ceca54aaee3fd912c02826a16c46f35f374a430e2df1750425"

      def install
        bin.install "lnk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/lnk/releases/download/v0.5.0/lnk_Linux_x86_64.tar.gz"
      sha256 "97c7c5c18f2f9d29caf5976019a2a12a24a5880fcbc0e97637c8c6e9676346af"
      def install
        bin.install "lnk"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/lnk/releases/download/v0.5.0/lnk_Linux_arm64.tar.gz"
      sha256 "aa11c210cc935b5f79f8d0e7c4f43e6b605fba16ee0568724af0f87a8714b4a7"
      def install
        bin.install "lnk"
      end
    end
  end

  test do
    system "#{bin}/lnk --version"
  end
end
